services:
  mysql:
    image: mysql:8.4
    container_name: blueberrytrace-mysql
    environment:
      MYSQL_DATABASE: vlv_blueberry_system
      MYSQL_ROOT_PASSWORD: 12345678
    ports:
      - "3306:3306"
    volumes:
      - blueberrytrace_mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: blueberrytrace-app
    depends_on:
      - mysql
    environment:
      DB_URL: jdbc:mysql://mysql:3306/vlv_blueberry_system?useSSL=false&serverTimezone=America/Lima&allowPublicKeyRetrieval=true
      DB_USERNAME: root
      DB_PASSWORD: 12345678
      SERVER_PORT: 8080
    ports:
      - "8080:8080"

volumes:
  blueberrytrace_mysql_data:
