import { useMemo, useState } from 'react';
import { Droplets, Leaf, Plus, Save, Sprout, XCircle } from 'lucide-react';
import { ConfirmDialog } from '../components/ConfirmDialog';
import { EmptyState } from '../components/EmptyState';
import { FormMessage, FormSection } from '../components/FormLayout';
import { Modal } from '../components/Modal';
import { ModuleHeader } from '../components/ModuleHeader';
import { StatusBadge } from '../components/StatusBadge';
import { blueberryApi } from '../lib/api';
import { dateShort, numberCompact } from '../lib/format';
import { emitToast } from '../lib/uiEvents';
import type { JabaResponse, LoteTrazableResponse, RecuperacionRiegoFormPayload, RecuperacionRiegoResponse, RecuperacionRiegoStatusPayload } from '../types/api';

interface RecuperacionesPageProps { recuperaciones: RecuperacionRiegoResponse[]; lotesTrazables: LoteTrazableResponse[]; jabas: JabaResponse[]; onChanged: (items: RecuperacionRiegoResponse[]) => void; }
const today = () => new Date().toISOString().slice(0, 10);

export function RecuperacionesPage({ recuperaciones, lotesTrazables, jabas, onChanged }: RecuperacionesPageProps) {
  const [createOpen, setCreateOpen] = useState(false);
  const [closing, setClosing] = useState<RecuperacionRiegoResponse | null>(null);
  const [saving, setSaving] = useState(false);
  async function create(payload: RecuperacionRiegoFormPayload) { setSaving(true); try { const response = await blueberryApi.createRecuperacionRiego(payload); onChanged(response.items); setCreateOpen(false); emitToast('success', 'Recuperación registrada', 'Las plantas quedan en seguimiento de riego antes de retornar al proceso.'); } finally { setSaving(false); } }
  async function close(payload: RecuperacionRiegoStatusPayload) { if (!closing) return; setSaving(true); try { const response = await blueberryApi.closeRecuperacionRiego(closing.id, payload); onChanged(response.items); setClosing(null); emitToast('success', 'Recuperación cerrada', 'Se registró el resultado de las plantas recuperadas y descartadas.'); } finally { setSaving(false); } }
  const ongoing = recuperaciones.filter((item) => item.estado === 'EN_RIEGO');
  return <main className="content-grid">
    <ModuleHeader eyebrow="Cuidado de plantas" title="Recuperación por riego" description="Registra plantas secas u observadas que vuelven a riego antes de retornar a uniformización o clasificación. Las plantas derivadas desde uniformización o clasificación se registran automáticamente." icon={<Droplets size={21} />} tone="blue" actions={<button type="button" className="action-button" onClick={() => setCreateOpen(true)}><Plus size={16} /> Enviar a riego</button>} />
    <section className="summary-strip summary-strip--three"><article className="summary-pill summary-pill--blue"><span className="summary-pill__icon"><Droplets size={18} /></span><span>En recuperación</span><strong>{ongoing.reduce((sum, item) => sum + item.cantidadIngresada, 0)}</strong><small>plantas</small></article><article className="summary-pill summary-pill--green"><span className="summary-pill__icon"><Leaf size={18} /></span><span>Registros cerrados</span><strong>{recuperaciones.filter((item) => item.estado !== 'EN_RIEGO').length}</strong><small>registros</small></article><article className="summary-pill summary-pill--orange"><span className="summary-pill__icon"><XCircle size={18} /></span><span>Descartadas</span><strong>{recuperaciones.reduce((sum, item) => sum + (item.cantidadDescartada || 0), 0)}</strong><small>plantas</small></article></section>
    <section className="panel-card"><div className="panel-card__header"><div><h2>Seguimiento de recuperación</h2><p>Las plantas recuperadas pueden volver a uniformización o clasificación según el resultado de riego.</p></div><span className="panel-card__count">{recuperaciones.length} registros</span></div>{recuperaciones.length ? <div className="data-table-wrap"><table className="data-table"><thead><tr><th>Lote trazable</th><th>Jaba</th><th>Origen → retorno</th><th>Ingreso</th><th>Cantidad</th><th>Estado</th><th /></tr></thead><tbody>{recuperaciones.map((item) => <tr key={item.id}><td>{item.loteTrazable?.codigo || 'Sin lote'}</td><td>{item.jaba?.codigo || 'Sin jaba'}</td><td>{item.etapaOrigen} → {item.etapaRetorno}</td><td>{dateShort(item.fechaIngresoRiego)}</td><td>{numberCompact(item.cantidadIngresada)} <small>recup.: {numberCompact(item.cantidadRecuperada || 0)} · desc.: {numberCompact(item.cantidadDescartada || 0)}</small></td><td><StatusBadge value={item.estado} /></td><td>{item.estado === 'EN_RIEGO' ? <button type="button" className="ghost-button ghost-button--small" onClick={() => setClosing(item)}>Cerrar resultado</button> : null}</td></tr>)}</tbody></table></div> : <EmptyState icon={<Droplets size={28} />} title="No hay plantas en recuperación" description="Cuando se encuentren plantas secas durante uniformización o clasificación, regístralas aquí para controlar su riego." action={<button className="action-button" type="button" onClick={() => setCreateOpen(true)}><Plus size={15} /> Enviar a riego</button>} />}</section>
    <Modal open={createOpen} title="Enviar plantas a recuperación por riego" description="Registra el grupo de plantas secas u observadas y la etapa a la que volverán después del riego." onClose={() => setCreateOpen(false)}><RecoveryCreateForm traces={lotesTrazables} jabas={jabas} saving={saving} onSubmit={create} onCancel={() => setCreateOpen(false)} /></Modal>
    <Modal open={Boolean(closing)} title="Cerrar recuperación por riego" description="Antes de cerrar, registra un riego de recuperación realizado. Las plantas recuperadas y descartadas deben sumar exactamente la cantidad enviada a riego." onClose={() => setClosing(null)}>{closing ? <RecoveryCloseForm recovery={closing} saving={saving} onSubmit={close} onCancel={() => setClosing(null)} /> : null}</Modal>
  </main>;
}

function RecoveryCreateForm({ traces, jabas, saving, onSubmit, onCancel }: { traces: LoteTrazableResponse[]; jabas: JabaResponse[]; saving: boolean; onSubmit: (payload: RecuperacionRiegoFormPayload) => Promise<void>; onCancel: () => void }) {
  const first = traces[0]; const [payload, setPayload] = useState<RecuperacionRiegoFormPayload>({ loteTrazableId: first?.id || 0, jabaId: jabas.find((item) => item.cama?.id === first?.camaInicial?.id)?.id, etapaOrigen: 'FORMALIZACION', etapaRetorno: 'UNIFORMIZACION', fechaIngresoRiego: today(), cantidadIngresada: 1, observacion: '' }); const [error,setError]=useState<string|null>(null);
  const trace=traces.find((item)=>item.id===payload.loteTrazableId); const traceJabas=jabas.filter((item)=>item.cama?.id===trace?.camaInicial?.id && item.estado==='ACTIVA');
  function selectTrace(id:number){const selected=traces.find((item)=>item.id===id); const next=jabas.find((item)=>item.cama?.id===selected?.camaInicial?.id && item.estado==='ACTIVA'); setPayload((current)=>({...current,loteTrazableId:id,jabaId:next?.id}));}
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();try{setError(null);await onSubmit({...payload,observacion:payload.observacion?.trim()||undefined});}catch(exception){setError(exception instanceof Error?exception.message:'No fue posible registrar la recuperación.');}}
  return <form className="form-shell" onSubmit={submit}>{error?<FormMessage>{error}</FormMessage>:null}<FormSection title="Plantas a recuperar" description="Mantén el vínculo con la jaba donde se detectaron plantas secas. Si el hallazgo ocurrió durante una uniformización registrada, el sistema crea este seguimiento automáticamente." icon={<Droplets size={18} />}><div className="form-grid form-grid--two"><label className="form-grid__full"><span>Lote trazable</span><select value={payload.loteTrazableId} onChange={(event)=>selectTrace(Number(event.target.value))}><option value={0} disabled>Selecciona un lote</option>{traces.map((item)=><option key={item.id} value={item.id}>{item.codigo} · {item.variedad}</option>)}</select></label><label><span>Jaba</span><select value={payload.jabaId||0} onChange={(event)=>setPayload({...payload,jabaId:Number(event.target.value)})}><option value={0}>No especificar</option>{traceJabas.map((item)=><option key={item.id} value={item.id}>{item.codigo}</option>)}</select></label><label><span>Fecha de ingreso a riego</span><input type="date" value={payload.fechaIngresoRiego} onChange={(event)=>setPayload({...payload,fechaIngresoRiego:event.target.value})} required /></label><label><span>Etapa donde se detectaron</span><select value={payload.etapaOrigen} onChange={(event)=>setPayload({...payload,etapaOrigen:event.target.value})}><option value="UNIFORMIZACION">Uniformización</option><option value="FORMALIZACION">Formalización</option><option value="CLASIFICACION">Clasificación</option></select></label><label><span>Retornarán a</span><select value={payload.etapaRetorno} onChange={(event)=>setPayload({...payload,etapaRetorno:event.target.value})}><option value="UNIFORMIZACION">Uniformización</option><option value="CLASIFICACION">Clasificación</option></select></label><label><span>Cantidad de plantas</span><input type="number" min={1} value={payload.cantidadIngresada} onChange={(event)=>setPayload({...payload,cantidadIngresada:Number(event.target.value)})} /></label><label className="form-grid__full"><span>Observación</span><textarea value={payload.observacion||''} onChange={(event)=>setPayload({...payload,observacion:event.target.value})} placeholder="Ejemplo: plantas secas, requiere riego programado" /></label></div></FormSection><footer className="form-actions form-actions--sticky"><button type="button" className="ghost-button" onClick={onCancel} disabled={saving}>Cancelar</button><button type="submit" className="action-button" disabled={saving||!payload.loteTrazableId}>{saving?'Guardando...':<><Save size={16}/> Registrar recuperación</>}</button></footer></form>;
}

function RecoveryCloseForm({ recovery, saving, onSubmit, onCancel }: { recovery: RecuperacionRiegoResponse; saving: boolean; onSubmit: (payload: RecuperacionRiegoStatusPayload) => Promise<void>; onCancel: () => void }) {
 const [recovered,setRecovered]=useState(recovery.cantidadIngresada); const [discarded,setDiscarded]=useState(0); const [reason,setReason]=useState(''); const [observation,setObservation]=useState(recovery.observacion||''); const [error,setError]=useState<string|null>(null);
 async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(recovered+discarded!==recovery.cantidadIngresada){setError('Las plantas recuperadas y descartadas deben sumar la cantidad ingresada.');return;}if(discarded>0&&!reason.trim()){setError('Indica el motivo de descarte.');return;}try{setError(null);await onSubmit({cantidadRecuperada:recovered,cantidadDescartada:discarded,motivoDescarte:reason.trim()||undefined,observacion:observation.trim()||undefined});}catch(exception){setError(exception instanceof Error?exception.message:'No fue posible cerrar la recuperación.');}}
 return <form className="form-shell" onSubmit={submit}>{error?<FormMessage>{error}</FormMessage>:null}<FormSection title="Resultado de recuperación" description={`Ingreso registrado: ${recovery.cantidadIngresada} plantas. Confirma este resultado después de registrar el riego realizado.`} icon={<Sprout size={18}/>}><div className="form-grid form-grid--two"><label><span>Plantas recuperadas</span><input type="number" min={0} value={recovered} onChange={(event)=>setRecovered(Number(event.target.value))}/></label><label><span>Plantas descartadas</span><input type="number" min={0} value={discarded} onChange={(event)=>setDiscarded(Number(event.target.value))}/></label>{discarded>0?<label className="form-grid__full"><span>Motivo de descarte</span><input value={reason} onChange={(event)=>setReason(event.target.value)} maxLength={120} required /></label>:null}<label className="form-grid__full"><span>Observación final</span><textarea value={observation} onChange={(event)=>setObservation(event.target.value)} /></label></div></FormSection><footer className="form-actions form-actions--sticky"><button type="button" className="ghost-button" onClick={onCancel} disabled={saving}>Cancelar</button><button type="submit" className="action-button" disabled={saving}>{saving?'Guardando...':<><Save size={16}/> Cerrar recuperación</>}</button></footer></form>;
}
